CREATE DATABASE LIBRARY
GO
USE LIBRARY
GO
CREATE TABLE BOOK
(
	F_ID CHAR(4),
	F_NAME NVARCHAR(100),
	F_TYPE NVARCHAR(100),
	F_AUTHOR NVARCHAR(100),
	PUBLISH_YEAR SMALLINT,
	DOCUMENT 
	PRIMARY KEY (F_ID)
)