CREATE DATABASE LIBRARYDB

GO
USE LIBRARYDB

GO
CREATE TABLE BOOK 
(
	ID VARCHAR(50),
	NAMEOFBOOK NVARCHAR(200),
	NAMEOFAUTHOR NVARCHAR(200),
	PUBLISHYEAR INT,
	LINK NVARCHAR(200),
	TYPEOFBOOK NVARCHAR(50),
	PRIMARY KEY (ID)
)
GO
INSERT INTO BOOK VALUES ('001', 'Creative Writing for Dummies', 'Maggie Hamand','2010', NULL, 'STUDY')
INSERT INTO BOOK VALUES ('002', 'Blogging for Dummies', 'Brad Hill','2010', NULL, 'STUDY')
INSERT INTO BOOK VALUES ('003', 'Public Speaking for Dummies', 'Malcolm Kushner','1998', NULL, 'STUDY')
INSERT INTO BOOK VALUES ('004', 'Guitar For Dummies', 'Mark Phillips','1998', NULL, 'STUDY')
INSERT INTO BOOK VALUES ('005', 'Technical Writing For Dummies', 'Sheryl Lindsell-Roberts (Contributor)','2001', NULL, 'STUDY')

SELECT * FROM BOOK WHERE ID = '001'
SELECT * FROM BOOK WHERE NAMEOFBOOK = 'Technical Writing For Dummies'

SELECT * FROM BOOK WHERE NAMEOFAUTHOR = 'Mark Phillips'
SELECT * FROM BOOK WHERE TYPEOFBOOK = 'STUDY'

UPDATE BOOK SET LINK = 'D:\SOCKET_PROJ\Server\books\dm1.txt' WHERE ID = '001'
UPDATE BOOK SET LINK = 'D:\SOCKET_PROJ\Server\books\dm2.txt' WHERE ID = '002'
UPDATE BOOK SET LINK = 'D:\SOCKET_PROJ\Server\books\dm3.txt' WHERE ID = '003'
UPDATE BOOK SET LINK = 'D:\SOCKET_PROJ\Server\books\dm4.txt' WHERE ID = '004'
UPDATE BOOK SET LINK = 'D:\SOCKET_PROJ\Server\books\dm5.txt' WHERE ID = '005'